pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('8893faf4-5148-4656-ac90-e80ab664b8aa')
        IMAGE_NAME = "dockpavan/app-1"
        DOCKERFILE_PATH = "./Dockerfile"
    }

    stages {
        stage('Checkout') {
            steps {
                // Checkout the code from version control
                checkout changelog: false, poll: false, scm: scmGit(branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/pavankumarBL/Dummy_proj.git']])
            }
        }
        
        stage('Build Docker Image') {
            steps {
                script {
                    // Build the Docker image
                    docker.build("${env.IMAGE_NAME}:${env.BUILD_NUMBER}", "-f ${DOCKERFILE_PATH} .")
                }
            }
        }
        
        stage('Push Docker Image') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'DOCKERHUB_CREDENTIALS') {
                        // Push the Docker image to DockerHub
                        docker.image("${env.IMAGE_NAME}:${env.BUILD_NUMBER}").push()
                    }
                }
            }
        }

        stage('Clean Up') {
            steps {
                script {
                    // Clean up local Docker images to save space
                    sh "docker rmi ${env.IMAGE_NAME}:${env.BUILD_NUMBER}"
                }
            }
        }
    }

    post {
        always {
            // Clean up workspace after build
            cleanWs()
        }
    }
}
